In [43]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
from word2number import w2n
import seaborn as sns

In [44]:
data_hire = pd.read_csv(r"C:\Users\DELL\Desktop\ML Youtube\hiring.csv")

In [45]:
data_hire

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [46]:
test_median = data_hire["test_score(out of 10)"].median()

In [47]:
test_median

8.0

In [48]:
data_hire["test_score(out of 10)"] = data_hire["test_score(out of 10)"].fillna(test_median)

In [49]:
data_hire

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [50]:
data_hire["experience"] = data_hire["experience"].fillna("zero")

In [51]:
data_hire

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [52]:
data_hire["experience"] = data_hire["experience"].apply(w2n.word_to_num)

In [53]:
data_hire

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

# Problem statement

# In exercise folder (same level as this notebook on github) there is hiring.csv. This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,

# Creating a linear regression object.

In [55]:
reg = linear_model.LinearRegression()
reg

LinearRegression()

# Fit the model and train the data set.

In [56]:
reg.fit(data_hire[["experience" , "test_score(out of 10)" , "interview_score(out of 10)"]] , data_hire["salary($)"])

LinearRegression()

# Coefficients

In [59]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

# Intercept

In [60]:
reg.intercept_

17737.263464337688

# Problem 1
# 2 yr experience, 9 test score, 6 interview score

In [57]:
reg.predict([[2,9,6]])

array([53205.96797671])

# problem 2
# 12 yr experience, 10 test score, 10 interview score

In [58]:
reg.predict([[12 , 10 , 10]])

array([92002.18340611])